parameters:
  oxid_esales.theme.admin.name: 'admin_twig'

services:
  OxidEsales\Eshop\Core\Config:
    factory: ['OxidEsales\Eshop\Core\Registry', getConfig]

  OxidEsales\Eshop\Core\UtilsView:
    factory: ['OxidEsales\Eshop\Core\Registry', getUtilsView]

  OxidEsales\Twig\TwigContextInterface:
    class: OxidEsales\Twig\TwigContext
    autowire: true
    public: true

  OxidEsales\Twig\TwigEngineConfigurationInterface:
    class: OxidEsales\Twig\TwigEngineConfiguration
    arguments:
      - '@OxidEsales\Twig\TwigContextInterface'
    public: true

  twig:
    class: Twig\Environment
    arguments:
      - '@twig.loader.chain'
      - "@=service('OxidEsales\\\\Twig\\\\TwigEngineConfigurationInterface').getParameters()"
    calls:
      - [addGlobal, ['twig', {capture: {}}]]
      - [addGlobal, ['oView', {}]]

  OxidEsales\Twig\TemplateLoaderNameParser:

  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateRendererBridgeInterface:
    class: OxidEsales\Twig\Bridge\TwigTemplateRendererBridge
    autowire: true
    public: true

  # Loaders

  twig.loader.filesystem:
    class: OxidEsales\Twig\Loader\FilesystemLoader
    arguments:
      - "@=service('OxidEsales\\\\Twig\\\\TwigContextInterface').getTemplateDirectories()"
      - null
      - "@oxid_esales.templating.template.loader"
      - "@oxid_esales.templating.admin.template.loader"
    tags: ['twig.loader']
    autowire: true

  OxidEsales\Twig\Loader\ContentTemplateLoader:
    arguments:
      - '@OxidEsales\Twig\TemplateLoaderNameParser'
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\ContentFactory'
    tags: ['twig.loader']

  twig.loader.chain:
    class: Twig\Loader\ChainLoader
    calls:
      - [addLoader, ['@twig.loader.filesystem']]
      - [addLoader, ['@OxidEsales\Twig\Loader\ContentTemplateLoader']]

  # Escapers

  OxidEsales\Twig\Escaper\DecEntityEscaper:
    tags: ['twig.escaper']

  OxidEsales\Twig\Escaper\HexEntityEscaper:
    tags: ['twig.escaper']

  OxidEsales\Twig\Escaper\HexEscaper:
    tags: ['twig.escaper']

  OxidEsales\Twig\Escaper\HtmlAllEscaper:
    tags: ['twig.escaper']

  OxidEsales\Twig\Escaper\MailEscaper:
    tags: ['twig.escaper']

  OxidEsales\Twig\Escaper\NonStdEscaper:
    tags: ['twig.escaper']

  OxidEsales\Twig\Escaper\QuotesEscaper:
    tags: ['twig.escaper']

  OxidEsales\Twig\Escaper\UrlPathInfoEscaper:
    tags: ['twig.escaper']

  # Token parsers

  OxidEsales\Twig\TokenParser\HasRightsTokenParser:
    arguments:
      - 'OxidEsales\Twig\Node\HasRightsNode'

  # Extensions

  OxidEsales\Twig\Extensions\MathExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\IncludeExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IncludeDynamicLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\SmartyCycleExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\MailtoExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\UrlExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\SeoUrlLogic'
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\AddUrlParametersLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\AssignAdvancedExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\AssignAdvancedLogic'
    tags: ['twig.extension']

  Twig_Extension_StringLoader:
    class: Twig_Extension_StringLoader
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\HasRightsExtension:
    arguments:
      - '@OxidEsales\Twig\TokenParser\HasRightsTokenParser'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\IfContentExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IfContentLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\FormatPriceExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatPriceLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\CatExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\EncloseExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\ScriptExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\ScriptLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\FormatDateExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatDateLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\DateFormatExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\DateFormatHelper'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\TranslateExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateFilterLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\TranslateExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateFunctionLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\FormatTimeExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatTimeLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\FileSizeExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FileSizeLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\StyleExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\StyleLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\TruncateExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TruncateLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\TranslateSalutationExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\TranslateSalutationLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\FormatCurrencyExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\FormatCurrencyLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\WordwrapExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\WordwrapLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\IncludeWidgetExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\IncludeWidgetLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\SmartWordwrapExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\SmartWordwrapLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\InputHelpExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\InputHelpLogic'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\PhpFunctionsExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\PhpFunctionsExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\Filters\RegexReplaceExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\CaptureExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\InsertNewBasketItemExtension:
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\TemplateLogic\InsertNewBasketItemLogicTwig'
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\InsertTrackerExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\GetRequestVariablesExtension:
    tags: ['twig.extension']

  OxidEsales\Twig\Extensions\InheritanceHierarchyExtension:
    arguments:
      - '@OxidEsales\Twig\Resolver\TemplateHierarchyResolverInterface'
    tags: ['twig.extension']

  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateEngineInterface:
    class: OxidEsales\Twig\TwigEngine
    arguments:
      - '@twig'
      - !tagged twig.extension
      - !tagged twig.escaper
    public: false

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Resolver\TemplateNameResolverInterface:
    class: OxidEsales\Twig\Resolver\TemplateNameResolver
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Framework\Templating\Resolver\TemplateNameResolver'

  OxidEsales\Twig\Resolver\TemplateHierarchyResolverInterface:
    class: OxidEsales\Twig\Resolver\TemplateHierarchyResolver
    autowire: true
