install:
  composer:
    early: 'skip'
    transform: |
      {
        "config": {
          "github-protocols": ["https"]
        },
        "preferred-install": {
          "oxid-esales/*": "source"
        },
        "require": {
          "oxid-esales/apex-theme": "~v3.1.0",
          "oxid-esales/oxideshop-ce": "~v7.5.1",
          "oxid-esales/twig-admin-theme": "~v3.1.0",
          "oxid-esales/twig-component": "~v2.8.1"
        },
        "require-dev":{
          "mikey179/vfsstream": "~1.6.8",
          "oxid-esales/developer-tools": "{{ .Data.install.composer.dev_ref }}",
          "phpspec/prophecy-phpunit": "^v2.0.1",
          "phpunit/phpunit": "^12.5"
        },
        "autoload-dev":{
          "psr-4":{
            "OxidEsales\\Twig\\Tests\\": "./vendor/oxid-esales/twig-component/tests"
          }
        }
      }

runscript:
  matrix:
    script: |
      [
        "twig:~/unit.sh",
        "twig:~/integration.sh"
      ]
  composer:
    early: 'skip'
  twig:
    path: 'vendor/oxid-esales/twig-component'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Twig Component ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
