install:
  method: script
  script: 'source/vendor/oxid-esales/oxideshop-ce/.github/oxid-esales/install.sh'
  composer:
    early: 'skip'
    transform: |
      {
          "config": {
              "github-protocols": ["https"]
          },
          "preferred-install": {
            "oxid-esales/*": "source"
          },
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "dev-{{ .Data.global.git.safe_ref_name }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}"
          },
          "require-dev":{
              "oxid-esales/developer-tools":"{{ .Data.global.composer.dev_ref }}",
              "mikey179/vfsstream": "~1.6.8",
              "phpspec/prophecy-phpunit": "^v2.0.1",
              "phpunit/phpunit": "^11.4"
          },
          "autoload-dev":{
              "psr-4":{
                "OxidEsales\\Twig\\Tests\\": "./vendor/oxid-esales/twig-component/tests"
              }
          }
      }

runscript:
  matrix:
    script: |
      [
        "twig:~/unit.sh",
        "twig:~/integration.sh"
      ]
  composer:
    early: 'skip'
  twig:
    path: 'vendor/oxid-esales/twig-component'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Twig Component ({{ .Data.global.git.safe_ref_name }}) by {{ .Github.Actor }}'
  slack_compact: true
