install:
  git:
    sdk_ref: b-8.0.x
  method: script
  script: 'source/vendor/oxid-esales/twig-component/.github/oxid-esales/install.sh'
  composer:
    early: 'skip'
    transform: |
      {
        "config": {
          "github-protocols": ["https"]
        },
        "preferred-install": {
          "oxid-esales/*": "source"
        },
        "require": {
          "oxid-esales/oxideshop-composer-plugin": "dev-b-8.0.x-move-theme-settings-to-yaml-OXDEV-8895 as dev-b-8.0.x",
          "oxid-esales/apex-theme": "dev-b-8.0.x-move-theme-settings-to-yaml-OXDEV-8895",
          "oxid-esales/oxideshop-ce": "{{ .Data.install.composer.ref_name }}",
          "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.dev_ref }}",
          "oxid-esales/twig-component": "{{ .Data.install.composer.ref_name }}"
        },
        "require-dev":{
          "mikey179/vfsstream": "~1.6.8",
          "oxid-esales/developer-tools": "{{ .Data.install.composer.dev_ref }}",
          "phpspec/prophecy-phpunit": "^v2.0.1",
          "phpunit/phpunit": "^12.5"
        },
        "autoload-dev":{
          "psr-4":{
            "OxidEsales\\Twig\\Tests\\": "./vendor/oxid-esales/twig-component/tests"
          }
        }
      }

runscript:
  matrix:
    script: |
      [
        "twig:~/unit.sh",
        "twig:~/integration.sh"
      ]
  composer:
    early: 'skip'
  twig:
    path: 'vendor/oxid-esales/twig-component'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Twig Component ({{ .Data.install.git.ref }}) by {{ .Github.Actor }}'
