install: &install
  method: script
  script: 'source/.github/oxid-esales/install.sh'
  git:
    ref: '{{ .Data.global.git.default_ref }}'
  composer:
    early: 'skip'
    root_url: ''
    transform: |
      {
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source"
          },
          "require": {
            "oxid-esales/twig-component": "dev-{{ .Data.global.git.safe_ref_name }}",
            "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
            "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
            "twig/twig": "v3.8.0"
          }
      }
  output:
    files: |
      docker-compose.yml
      source/composer.json*
      source/composer.lock
      source/source/config.inc.php
      source/vendor/oxid-esales/oxideshop-ce/source/config.inc.php
      data/php/logs/error_log.txt

install_shop_with_modules: *install

runscript: &runscript
  matrix:
    script: |
      [
        "twig:~/unit.sh",
        "twig:~/integration.sh"
      ]
  twig:
    path: 'vendor/oxid-esales/twig-component'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Twig Component ({{ .Data.github.RefName }}) by {{ .Github.Actor }}'
  slack_compact: true
